on:
  pull_request:
  push:
    branches: [main]

jobs:
  XeLaTeX:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: xu-cheng/texlive-action/small@v1
        with:
          run: |
            tlmgr install ctex gbt7714 subfiles
            xelatex -interaction=nonstopmode -halt-on-error -file-line-error -synctex=1 main.tex
            bibtex main
            xelatex -interaction=nonstopmode -halt-on-error -file-line-error -synctex=1 main.tex
            xelatex -interaction=nonstopmode -halt-on-error -file-line-error -synctex=1 main.tex
      - uses: actions/upload-artifact@v3
        with:
          name: main.pdf
          path: main.pdf
